### ISSUE TITLE
Update TeadsSDK-adapter-admob-ios for Xcode 11

### ISSUE THREAD

**Issue by aoifemcl15** [teads/TeadsSDK-adapter-admob-ios#1]
Hi @HugoGresse , we are having issues using the Teads - iOS AdMob Mediation Adapter on Xcode 11.
We have set the TeadsSDK to use the 'xcode11b3' branch referenced here https://github.com/teads/TeadsSDK-iOS/issues/113. 
However we are experiencing an issue, captured below when trying to use the TeadsAdMobAdapter. 
![Screen Shot 2019-08-08 at 12 49 12](https://user-images.githubusercontent.com/53755195/62700909-f4a56580-b9da-11e9-9ffd-5da3401cdf7a.png)
Would it be possible to make a version of the TeadsSDK-adapter-admob-ios that builds on Xcode 11 available? 
Thanks

**Comment by HugoGresse** [comment]
Hi, we are waiting for the release candidate or the final XCode 11 to release any Teads framework supporting those version. 
Let us know if you need anything more.

**Comment by aoifemcl15** [comment]
Hi @HugoGresse, following the release of Xcode 11 GM on 10th September when do you estimate an update to TeadsSDK-adapter-admob-ios becoming available? 
Thanks

**Comment by HugoGresse** [comment]
There is no clear date for the moment but I'll update this ticket as soon as I have some visibility.

**Comment by sroddy** [comment]
@HugoGresse con you please publish the updated version(4.3.0) on Cocoapods?

**Comment by HugoGresse** [comment]
Hi Stefano. 
Yes, it's planned to be done today. I'll update this issue when it's done.

**Comment by HugoGresse** [comment]
Hi, the adapter & Teads SDK version 4.3.1 has been released. I'm closing the ticket but don't hesitate to contact us again if needed.
