### ISSUE TITLE
GADMAdapterTeadsInterstitial and GADMAdapterTeadsBanner need a `required` initializer

### ISSUE THREAD

**Issue by SLambrakis** [teads/TeadsSDK-adapter-admob-ios#4]
We have integrated GoogleMobileAdsMediationTeads version 4.6.3 via Cocoapods. When compiling a release build for generic device, we get the following errors:

_.../Pods/GoogleMobileAdsMediationTeads/TeadsAdMobAdapter.framework/Modules/TeadsAdMobAdapter.swiftmodule/arm64-apple-ios.swiftinterface:37:33: Initializer requirement 'init()' can only be satisfied by a 'required' initializer in non-final class 'GADMAdapterTeadsInterstitial'_

_.../Pods/GoogleMobileAdsMediationTeads/TeadsAdMobAdapter.framework/Modules/TeadsAdMobAdapter.swiftmodule/arm64-apple-ios.swiftinterface:54:33: Initializer requirement 'init()' can only be satisfied by a 'required' initializer in non-final class 'GADMAdapterTeadsBanner'_

I believe this would be fixed by changing lines 37/54 to `  @objc required override dynamic public init()
`

**Comment by elneruda** [comment]
Hello @SLambrakis, 

Thank you for submitting issue, do you still have issue? you can check ou our [latest](https://github.com/teads/TeadsSDK-adapter-admob-ios/releases/latest) release

**Comment by SLambrakis** [comment]
Thank you, we no longer have this issue.
